### ISSUE TITLE
u cant accept terms of service

### ISSUE THREAD

**Issue by zandervander** [myStitch14/Gorilla-tag-Walk-sim-mod#19]
pls add a button idk why the face button no work :(

**Comment by zandervander** [comment]
i have a control for face button it just dont work

**Comment by myStitch14** [comment]
ok so I cant do that but to fix it find a mod menu that works without a VR and it has "Accept terms of service" mod on it because they do exist I think there is one of those called "II's stupid menu" so you can try that. if you do, then press "Q" on your keyboard to open the menu then find the "Accept terms of service" mod

**Comment by zandervander** [comment]
Ok
